apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: app-kube
  name: app-kube
spec:
  replicas: 2
  selector:
    matchLabels:
      run: app-kube
  template:
    metadata:
      labels:
        run: app-kube
    spec:
      containers:
      - image: gcr.io/gcp-tech/app-kube:latest
        name: app-kube
        ports:
        - containerPort: 8080