steps:
#step 0
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/app-kube:$COMMIT_SHA', '.']
#step 1
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/app-kube:latest', '.']
#step 2
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/app-kube:$COMMIT_SHA']
#step 3
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'Kubernates_yamls/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
#step 4
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
   'set', 
   'image', 
   'deployment', 
   'app-kube', 
   'app-kube=gcr.io/$PROJECT_ID/app-kube:$COMMIT_SHA'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
# push images to Google Container Registry with tags
images: [
   'gcr.io/$PROJECT_ID/app-kube:$COMMIT_SHA',
   'gcr.io/$PROJECT_ID/app-kube:latest'
  ]